[package]
name = "lol-replay-server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
byteorder = "1.4"
env_logger = "0.9"
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
